package.json
src/index.html
src/main.js

remove echart

---

src/Home.vue
src/components/inputNumber/index.vue
src/demos/inputNumber.vue
src/main.js

try to commit the component of inputnumber @Softor

Inputnumber

---

src/Home.vue
src/components/DateRangePicker/index.vue
src/components/datepicker/index.vue
src/demos/DateRangePicker.vue
src/demos/datepicker.vue
src/main.js

daterangepicker

---

src/Home.vue
src/components/index.js
src/components/pageloading/index.vue
src/components/progress/index.vue
src/demos/pageloading.vue
src/demos/progress.vue
src/main.js

progress & pageloading

---

src/components/autocomplete/index.vue
src/components/pageloading/index.vue
src/components/progress/index.vue

运营平台中，与common中的show class名称冲突，优先展示了common中的show，导致组件初始化就展现了。

modify class name 

---

.gitignore
README.md
src/Home.vue
src/assets/demo/default.css
src/components/suggestion/index.vue
src/demos/homeContent.vue
src/demos/suggestion.vue

1. fix README.md and homecontent 
2. fix suggestion component name 
3. fix suggestion demo to avoid cross-origin error

fix README.md, fix suggestion demo to avoid cross-origin error

---

src/components/date-picker/src/panel/date-range.vue
src/components/date-picker/src/panel/date.vue
src/components/date-picker/src/panel/time-range.vue
src/demos/modal.vue
src/less/mixins/date-picker-base.less

fix some bugs #102

---

package.json
src/Home.vue
src/components/checkbox-group/src/checkbox-group.vue
src/components/checkbox/src/checkbox.vue
src/components/date-picker/src/picker/date-picker.vue
src/components/date-picker/src/picker/pickerMixin.js
src/components/date-picker/src/picker/time-picker.vue
src/components/form-item/index.js
src/components/form/index.js
src/components/form/src/form-item.vue
src/components/form/src/form.vue
src/components/index.js
src/components/input/src/input.vue
src/components/radio-group/src/radio-group.vue
src/components/select/src/select.vue
src/components/suggestion/src/suggestion.vue
src/components/textarea/src/textarea.vue
src/demos/form.vue
src/demos/modal.vue
src/less/components/form.less
src/less/components/index.less
src/less/mixins/checkbox.less
src/router.js

1. add form
2. fix #104 
3. fix some docs

add form, fix sug bug & some doc

---

build/webpack.npm.conf.js
build/webpack.npm.umd.conf.js
package.json
src/components/suggestion/src/suggestion.vue
src/demos/form.vue

fix #108 #107

---

build/banner.js
build/webpack.npm.conf.js
build/webpack.npm.umd.conf.js
package.json
src/components/index.esmodule.js

1. add banner for dist
2. remove version require in dist

add banner for dist

---

src/components/date-picker/src/panel/date-range.vue
src/components/date-picker/src/panel/date.vue
src/components/date-picker/src/panel/time-select.vue
src/components/date-picker/src/panel/time.vue
src/components/form/src/form-item.vue
src/components/modal/src/modal.vue
src/components/scrolltop/src/scrolltop.vue
src/components/select/src/select.vue
src/components/suggestion/src/suggestion-dropdown.vue
src/components/suggestion/src/suggestion.vue
src/less/components/pagination.less
src/less/transitions/fade.less
src/less/transitions/move.less
src/less/transitions/slide.less
src/less/transitions/zoom.less

1. fix transition name, add `x-` suffix to avoid pollution
2. fix #112 #113

fix transition name, fix #112 #113

---

src/components/message/index.js
src/components/notice/index.js
src/components/select/src/select.vue
src/less/transitions/move.less

1. fix #116 
2. fix transition name

fix #116 & transition name 

---

dist/xcui.css
dist/xcui.js
dist/xcui.umd.js
src/Home.vue
src/components/index.esmodule.js
src/components/steps/index.js
src/components/steps/src/steps-item.vue
src/components/steps/src/steps.vue
src/components/steps/src/symbol.js
src/demos/steps.vue
src/less/components/index.less
src/less/components/steps.less
src/router.js

已经修补之前提到下方所列的问题，并且添加了icon属性。
- 添加description属性
- less中颜色值改为变量
- 添加`white-space:normal`自动换行
- 修改两处demo说明

Steps组件开发（修补1）

---

src/components/popover/src/popover.vue
src/components/tooltip/src/tooltip.vue

fix popover & tooltip transition name

fix popover & tooltip transition name

---

src/components/tag-checkable/src/tag-checkable.vue
src/components/tag/src/tag.vue
src/demos/tag.vue

1、修复了tag-checkable组件的checked只有第一次生效的问题 #130 
2、增加了tag组件的on-close回调的新特性 #131

增加了tag&tag-checkable组件的特性改进和bug修复

---

src/components/suggestion/src/suggestion.vue

fix suggestion handleEnter 

---

src/components/pagination/index.vue

修复pagination-pageSize不即时更新的问题 修复#141

---

build/webpack.dev.conf.js
demos/components/datepicker.vue
demos/components/datetimepicker.vue
src/components/date-picker/src/picker/pickerMixin.js

```js
pickeroptions: {
dateLimit: {
year: number,
month: number,
day: number,
hour: number,
minute: number,
second: number 
}
```

add datepicker&datetimepicker dateLimit support

---

demos/Home.vue
demos/assets/demo/demo.less
demos/components/dropdown.vue
demos/components/form.vue
demos/router.js
src/components/dropdown-item/index.js
src/components/dropdown-menu/index.js
src/components/dropdown/index.js
src/components/dropdown/src/dropdown-item.vue
src/components/dropdown/src/dropdown-menu.vue
src/components/dropdown/src/dropdown.vue
src/components/index.esmodule.js
src/less/components/dropdown.less
src/less/components/index.less

add dropdown

---

demos/components/table.vue
src/components/table/src/table-column.vue
src/components/table/src/tbody.js
src/components/table/src/thead.js

当表头需要分组，可以通过对表头多层嵌套实现，并支持对列动态赋值

Story2 合入多级表头部分

---

demos/components/alert.vue

update alert demo

---

demos/components/table.vue
src/components/table/src/table.vue

修复 x-table 高度不随数据变化而更新

---

demos/components/installation.vue

[folder] dist => lib  due to npm package folder changes

fix installation

---

src/components/date-picker/src/picker/pickerMixin.js

fix datepicker & datetimepicker error when select range & click confirm button
(no `pickeroptions` provided)

[datepicker] fix dateLimit bug

---

demos/components/tag.vue
src/components/tag-checkable/src/tag-checkable.vue
src/components/tag/src/tag.vue
src/less/components/tag.less

add tag disabled state

---

src/components/table/src/table.vue

修复了 table 状态不随 initial-selected-value-list、 initial-selected-value 改变更新的问题

add watch table props

---

package-lock.json
src/components/table/src/table-column.vue

fix dynamic column bug

---

src/components/collapse/src/collapse-item.vue
src/utils/collapse-transition.js

修复 Collapse 不随数据变化而更新问题

---

src/components/modal/src/modal.vue

modal组件在v-model默认为true时没有显示，只有在触发watch时才显示。

set modal show when v-model default set to true

---

demos/Home.vue
demos/components/breadcrumb.vue
demos/router.js
src/components/breadcrumb-item/index.js
src/components/breadcrumb/index.js
src/components/breadcrumb/src/breadcrumb-item.vue
src/components/breadcrumb/src/breadcrumb.vue
src/components/index.js
src/less/components/breadcrumb.less
src/less/components/index.less

breadcrumb done

---

src/components/scrolltop/src/scrolltop.vue

standard code for scrolltop

---

demos/components/suggestion.vue
src/components/suggestion/src/suggestion.vue

1. 增加匹配大小写参数`matchCase`
当建议数据源包含英文时可能会有不区分大小写的需求，而当前实现严格匹配大小写。
2. 增加匹配输入内容参数`matchInput`
某些情况下不需要前端对数据源进行过滤，完全展示`suggestions`数据源。比如远程请求数据源执行后台sug时，sug规则可能不再是简单的根据字符匹配，这时不再需要前端过滤

enhance suggestion

---

src/components/collapse/src/collapse.vue
src/components/tabs/src/tabs.vue

由
```
value: {
type: [Array, String, Number],
default:  []
}
```
改为
```
value: {
type: [Array, String, Number],
default: () => []
}
```

修改collapse声明默认props的方式

---

demos/components/suggestion.vue
demos/components/table.vue
demos/components/upload.vue
src/components/suggestion/src/suggestion.vue
src/components/upload/src/upload.vue
src/less/components/upload.less

upload选框样式更改&支持删除前回调；
table demo 更换slot-scope 支持vue 2.5+；
suggestion 修复change重复触发，text值变更后value值变更不及时bug，添加在线sug防抖优化请求次数，增加wait API设置防抖时间；

upload & suggestion & table demo bug修复组件升级；

---

src/components/collapse/src/collapse.vue
src/components/pagination/index.vue
src/components/tabs/src/tabs.vue

 修正无数据情况下next按钮可点问题

---

demos/components/suggestion.vue
demos/components/upload.vue
package-lock.json
src/components/date-picker/src/panel/date-range.vue
src/components/date-picker/src/panel/date.vue
src/components/suggestion/src/suggestion-dropdown.vue
src/components/suggestion/src/suggestion.vue
src/components/upload/src/formData-upload.vue
src/components/upload/src/upload-list.vue
src/components/upload/src/upload.vue
src/less/components/suggestion.less

xcui suggestion

---

src/components/suggestion/src/suggestion.vue

1. sug里复制带空格内容时去空格处理
2. 修复初始化时sug列表的问题

修复sug的空格问题等bug

---

build/build-bundle.js
demos/components/customTheme.vue

update load as required
